### ISSUE TITLE
Fix the link to 'C libffi documentation'

### ISSUE THREAD

**Issue by maekawatoshiki** [tov/libffi-rs#25]
On [this page](https://docs.rs/libffi/1.0.1/libffi/raw/index.html), the link to [C libffi documentation](http://www.atmark-techno.com/%7Eyashi/libffi.html) looks expired.

**Comment by YorickPeterse** [comment]
https://sourceware.org/libffi/ doesn't seem to contain any links to official documentation. If anybody knows of a good place to link to, please submit a pull request :smile:
