### ISSUE TITLE
The crates.io version of libffi-rs no longer builds

### ISSUE THREAD

**Issue by GeorgeKT** [tov/libffi-rs#3]
You get these errors:
...
   Compiling bindgen v0.22.0
   Compiling libffi-sys v0.4.7
   Compiling libffi v0.4.0
error[E0432]: unresolved import `raw::FFI_DEFAULT_ABI`
   --> /home/joris/.cargo/registry/src/github.com-1ecc6299db9ec823/libffi-0.4.0/src/low.rs:118:24
    |
118 | pub use raw::{ffi_abi, FFI_DEFAULT_ABI, _ffi_type as ffi_type, ffi_status,
    |                        ^^^^^^^^^^^^^^^ no `FFI_DEFAULT_ABI` in `raw`

error[E0432]: unresolved import `middle::FFI_DEFAULT_ABI`
  --> /home/joris/.cargo/registry/src/github.com-1ecc6299db9ec823/libffi-0.4.0/src/high/mod.rs:71:26
   |
71 | pub use middle::{FfiAbi, FFI_DEFAULT_ABI};
   |                          ^^^^^^^^^^^^^^^ no `FFI_DEFAULT_ABI` in `middle`

error: aborting due to 2 previous errors

error: Could not compile `libffi`.

You need to publish a version on crates.io with this commit included:

https://github.com/tov/libffi-rs/commit/d4b6edfff4d013876b79e206c3658c2e04c7eedc

**Comment by tov** [comment]
Oops, thanks, I'll do it now.

**Comment by tov** [comment]
Okay, hopefully that should do it.

**Comment by GeorgeKT** [comment]
Yes, that fixes it.
