### ISSUE TITLE
Bump sys dependency?

### ISSUE THREAD

**Issue by aepsil0n** [tov/libffi-rs#5]
Related to tov/libffi-sys-rs#8

Since you fixed the issue above, it would be great if you could bump this library, too.

Thank you! :)

**Comment by aepsil0n** [comment]
Just realized that the dependency on 0.5.2 is also satisfied by 0.5.3. Just had to run `cargo update`. But I guess it still makes sense to bump the version nonetheless.

**Comment by tov** [comment]
Yeah, I was wondering about that. I've already started it, though, so libffi 0.6.1 will depend on libffi-sys 0.5.3.
