### ISSUE TITLE
LibFFI fails to build

### ISSUE THREAD

**Issue by Luthaf** [tov/libffi-rs#6]
I get the following error when trying to build libffi:

```
   Compiling libffi-sys v0.5.4
   Compiling libffi v0.6.1
error[E0432]: unresolved import `raw::ffi_status`
  --> /home/guillaume/.cargo/registry/src/github.com-1ecc6299db9ec823/libffi-0.6.1/src/low.rs:29:14
   |
29 |     use raw::ffi_status::*;
   |              ^^^^^^^^^^ Not a module `ffi_status`

error[E0599]: no associated item named `STRUCT` found for type `u32` in the current scope
   --> /home/guillaume/.cargo/registry/src/github.com-1ecc6299db9ec823/libffi-0.6.1/src/low.rs:190:35
    |
190 |     pub const STRUCT:  c_ushort = raw::ffi_type_enum::STRUCT as c_ushort;
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `libffi`.
warning: build failed, waiting for other jobs to finish...
```

Any idea where this could come from?

I am on Linux Centos 7, with the latest stable rustc.

**Comment by tov** [comment]
libffi-sys is using an updated version of bindgen. Maybe it's generating different bindings? I'll look into it—sorry for the trouble.

**Comment by Luthaf** [comment]
Yes, this was my guess too =). Thank you for the very quick answer!

**Comment by tov** [comment]
Git head libffi should build now, because it specifies an older version of libffi-sys. I can release libffi with that older version specified if you'd find that useful. Then I'm going to try to figure out how to make libffi work with the new generated bindings.

**Comment by Luthaf** [comment]
Who, that was quick! I am fine without a release, I just wan to play around so I can use git dependencies in Cargo.toml. Thanks again for your reactivity!

**Comment by tov** [comment]
Okay, it's fixed. I'll be releasing libffi 0.6.2 shortly, which should build against libffi-sys 0.6.0.

**Comment by Luthaf** [comment]
Sorry, I forgot to close the issue. Everything is working perfectly =)
