### ISSUE TITLE
Structure argument data gets corrupted on cloning `libffi::middle::Cif`

### ISSUE THREAD

**Issue by aapoalas** [tov/libffi-rs#61]
### Steps to reproduce
1. Create a `libffi::middle::Cif::new()` with one of the parameters containing a structure type argument.
2. Place the resulting `cif` into a struct that derives `Clone`.
3. Create a clone of the struct.
4. Using `cloned_struct.cif.as_raw_ptr()` observe the structure type argument's `libffi::low::ffi_type` data.

### Expected result
The `cif` in the copied struct should contain expected size, alignment and elements for .

### Actual result
The `cif` in the copy has zero's as its size and alignment.

**Comment by YorickPeterse** [comment]
Fixed in https://github.com/tov/libffi-rs/pull/62, which is released on crates.io.
