### ISSUE TITLE
libffi-rs fails to build on amazon linux

### ISSUE THREAD

**Issue by triptec** [tov/libffi-rs#8]
I'm trying to build an application that uses libffi-rs to use in a aws lambda function. I've spent quite some time on this the last two weeks and I just can't get it to work. Works fine on ubuntu and manjaro when I've tried on those.

The output I get is [here](https://github.com/triptec/libffi-amzn/blob/master/log.txt) 

I've tried to distill this as much as I can and have made a repo a with a simple rust project and a Dockerfile, just run `./build.sh && ./run.sh` and it will build the image and then run cargo run within the container.

I you would find the time to take a look I would be very grateful.

Also thanks for your work on this lib

**Comment by tov** [comment]
That sounds frustrating! Unfortunately I won’t be able to look at this for real for a few days, but the output you linked provides a clue. The symbol it's complaining about is defined by libffi [here](https://github.com/libffi/libffi/blob/master/src/types.c#L69). So it's weird that it's not finding it, unless that's the first symbol among many that it would fail to find? I'm not sure. But the other thing I notice is that the final linking command that's failing doesn't include `-lffi` at all (nor does anything else in that log), and I think it should. Does it in other settings, where it doesn’t fail? (Or does the libffi_sys rlib link against libffi.a statically?)

**Comment by triptec** [comment]
Well in this small example that's the only symbol I've included but in the real project all used symbols from libffi fails to be found.
Also the reason -lffi isn't included in the final linking command is (I believe) that libffi-sys-rs actually builds libffi from source that is included in the libffi-sys-rs as a git submodule and the result of that compilation is pointed out by the " -L /src/target/debug/build/libffi-sys-58acd9945774872e/out/libffi-root/lib -L /src/target/debug/build/libffi-sys-58acd9945774872e/out/libffi-root/lib64" part.
Also I've made another [repo](https://github.com/triptec/libffi-u) just using ubuntu instead and the [output](https://github.com/triptec/libffi-u/blob/master/log.txt) from what I can tell is the same except it doesn't fail.
When libffi-sys-rs is compiled it has ` -l static=ffi` among the flags and I would guess that links libffi.a statically though I'm in deep waters here.

Anyhow thanks for your time and if it means waiting a few days to find a solution it's something I gladly do.

**Comment by triptec** [comment]
So I've looked at the output of "nm" to see if the symbols exists in [libffi.a](https://github.com/triptec/libffi-amzn/blob/master/libffi.a.symbols.txt) and [libffi.so](https://github.com/triptec/libffi-amzn/blob/master/libffi.so.symbols.txt) and indeed they are there.

I've also learned that the order of objects when linking matters so that would be interesting to look into but I'm really not sure how to change linking order in cargo (only tool I use)

**Comment by tov** [comment]
I'm not sure how to tell Cargo to link in a different order, but you can see the link command it's running and try running permutations of that my hand.

Also, I wonder what `nm` says about the various things being linked by that final linking command. Though if the symbols in question are in an rlib, I don't know how to look inside that.

Also, I don't know anything about the AWS/lambda environment. Is it pretty weird?

**Comment by triptec** [comment]
using strace i found this is how ld is called, not sure there's any useful info but what do I know
``` 
#amzn
/usr/bin/ld --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e /usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/Scrt1.o /usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/crti.o /usr/lib/gcc/x86_64-amazon-linux/4.8.3/crtbeginS.o -L/root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib -L/src/target/debug/deps -L/src/target/debug/build/libffi-sys-58acd9945774872e/out/libffi-root/lib -L/src/target/debug/build/libffi-sys-58acd9945774872e/out/libffi-root/lib64 -L/root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib -L/usr/lib/gcc/x86_64-amazon-linux/4.8.3 -L/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../.. --as-needed -z noexecstack /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.1n1u043hvq6vjmyq.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.2m1zcec3g1o58o5a.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.2r5l5l874xm2ybho.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.33ijuy7ny1ocv4tp.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.3p7qzswy0mvrpo8r.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.4g57x9clq3sforzb.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.5dadv1evmbogywnd.rcgu.o --gc-sections -zrelro -znow -Bstatic /src/target/debug/deps/liblibffi-22114aafb9eef8d3.rlib /src/target/debug/deps/liblibffi_sys-bd559f8a262dfae1.rlib /src/target/debug/deps/liblibc-49802dcd396439e8.rlib /src/target/debug/deps/libabort_on_panic-aa495b1080d3d180.rlib --start-group /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-e39317eb74365d3c.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-4d55a38564aae54a.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-f8521075e248b627.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-7c91ffdc8da860d3.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-0ad27b9879d551d3.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-588f18eae3ea58be.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-4ebf5caee903d98f.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-8895b32baedb08c6.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-6a9d233d01acc350.rlib --end-group /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-851bb3b5f6c4db49.rlib -Bdynamic -lutil -lutil -ldl -lrt -lpthread -lgcc_s -lc -lm -lrt -lpthread -lutil -lutil /usr/lib/gcc/x86_64-amazon-linux/4.8.3/crtendS.o /usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/crtn.o

#ubuntu
/usr/bin/ld -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccMqnEMD.res --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o -L/root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib -L/src/target/debug/deps -L/src/target/debug/build/libffi-sys-58acd9945774872e/out/libffi-root/lib -L/src/target/debug/build/libffi-sys-58acd9945774872e/out/libffi-root/lib64 -L/root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. --as-needed -z noexecstack /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.1n1u043hvq6vjmyq.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.2m1zcec3g1o58o5a.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.2r5l5l874xm2ybho.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.33ijuy7ny1ocv4tp.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.3p7qzswy0mvrpo8r.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.4g57x9clq3sforzb.rcgu.o /src/target/debug/deps/libffi_amzn-8649bdb0f5241a9e.5dadv1evmbogywnd.rcgu.o --gc-sections -zrelro -znow -Bstatic /src/target/debug/deps/liblibffi-22114aafb9eef8d3.rlib /src/target/debug/deps/liblibffi_sys-bd559f8a262dfae1.rlib /src/target/debug/deps/liblibc-49802dcd396439e8.rlib /src/target/debug/deps/libabort_on_panic-aa495b1080d3d180.rlib --start-group /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-e39317eb74365d3c.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-4d55a38564aae54a.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-f8521075e248b627.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-7c91ffdc8da860d3.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-0ad27b9879d551d3.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-588f18eae3ea58be.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-4ebf5caee903d98f.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-8895b32baedb08c6.rlib /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-6a9d233d01acc350.rlib --end-group /root/.rustup/toolchains/1.33.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-851bb3b5f6c4db49.rlib -Bdynamic -lutil -lutil -ldl -lrt -lpthread -lgcc_s -lc -lm -lrt -lpthread -lutil -lutil /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o
```

**Comment by triptec** [comment]
I missed your response but yeah now that I have the linking args I will fiddle with that a little bit.
But first I think I will see if I can point out the libffi.a or libffi.so directly to `ld` in some way.
Second I think I will try a newer amzn linux than the one that runs on lambda and see if it works there, if that doesn't work perhaps try centos 6 which it's supposed to be based on 

About the aws lambda environment I don't thing it's weird, mostly old I think (libffi is 3.0.13 with is from 2013), based on centos so it's yum to install things.

**Comment by triptec** [comment]
output from bindgen is somewhat different, on ubuntu where it works I get link_names like  [ link_name = "\u{1}ffi_type_void" ], but on amazonlinux it's [ link_name = "\u{1}_Z13ffi_type_void" ]

**Comment by triptec** [comment]
Finally!!
Adding .trust_clang_mangling(false) to the bindgen command in build.rs in libffi-sys-rs did the trick!

**Comment by tov** [comment]
Did the trick as in fixed the whole problem?

Do you know if changing that would work on other platforms? Should we change it only on Amazon Linux?

**Comment by triptec** [comment]
Yeah, fixed the whole problem.
About changing it for all platform, I'm running it on my local environment on manjaro and that seems work as well. I wonder what's the true problem, maybe it's just old versions of clang that should have it.

**Comment by YorickPeterse** [comment]
It's been a while since the last comment on this issue. In the upcoming libffi release we no longer depend on clang, so this shouldn't be a problem any more. I'll close this issue.
